describe('WEB UI Magento', () => {
    beforeEach ('Registrasi Akun', () => {
      cy.visit('https://magento.softwaretestingboard.com')
      cy.wait(5000)
    })
        //Positif Test
    it ('Registrasi Akun', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('Ega')
        cy.get('#lastname').type('safa')
        cy.get('#email_address').type('xxx@gmail.com')
        cy.get('#password').type('xxaarr123@')
        cy.get('#password-confirmation').type('xx123@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/')
})
    //Negatif test
    it ('Registrasi Akun - First Name  Null', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('null')
        cy.get('#lastname').type('safa')
        cy.get('#email_address').type('xxx@gmail.com')
        cy.get('#password').type('xx123@')
        cy.get('#password-confirmation').type('xx123@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/create')
    })
    it ('Registrasi Akun - lastname  Null', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('ega')
        cy.get('#lastname').type('null')
        cy.get('#email_address').type('xxx@gmail.com')
        cy.get('#password').type('aaxx11@')
        cy.get('#password-confirmation').type('aaxx11@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/create')
    }) 
    it ('Registrasi Akun - Email  Null', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('ega')
        cy.get('#lastname').type('safa')
        cy.get('#email_address').type('null')
        cy.get('#password').type('aaxx11@')
        cy.get('#password-confirmation').type('aaxx11@')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/create')
    }) 
    it ('Registrasi Akun - Password  Null', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('ega')
        cy.get('#lastname').type('safa')
        cy.get('#email_address').type('xxx@gmail.com')
        cy.get('#password').type('null')
        cy.get('#password-confirmation').type('null')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/create')
    })  
    it ('Registrasi Akun - Password  Not valid', () => {
        cy.get('.panel > .header > :nth-child(3) > a').click()
        cy.url().should('include', 'customer/account/create')
        cy.get('#firstname').type('ega')
        cy.get('#lastname').type('safa')
        cy.get('#email_address').type('xxx@gmail.com')
        cy.get('#password').type('aaxx11@')
        cy.get('#password-confirmation').type('aaxx11')
        cy.get('#form-validate > .actions-toolbar > div.primary > .action > span').click()
        cy.url().should('include', 'customer/account/create')
    })  
})
